#
# Marlin Firmware
# PlatformIO Configuration File
#
# See https://arduino-pico.readthedocs.io/en/latest/platformio.html
#

[env:RP2040]
platform         = raspberrypi
board            = pico
framework        = arduino
#board_build.core = earlephilhower
#lib_ldf_mode    = off
#lib_compat_mode = strict
build_src_filter = ${common.default_src_filter} +<src/HAL/RP2040>
lib_deps         = ${common.lib_deps}
                   arduino-libraries/Servo
                   https://github.com/pkElectronics/SoftwareSerialM#master
                   #adafruit/Adafruit TinyUSB Library
                   #lvgl/lvgl@^8.1.0
lib_ignore       = WiFi
build_flags      = ${common.build_flags} -D__PLAT_RP2040__ -DPLATFORM_M997_SUPPORT -DNO_SD_HOST_DRIVE -Wno-expansion-to-defined -Wno-vla -Wno-ignored-qualifiers
upload_protocol  = picotool
#custom_marlin.HAS_SD_HOST_DRIVE = tinyusb

[env:RP2040_PickSix]
platform         = raspberrypi
board            = marlin_RP2040_PickSix
framework        = arduino
extra_scripts    = ${common.extra_scripts}
                   pre:buildroot/share/PlatformIO/scripts/generic_create_variant.py
build_src_filter = ${common.default_src_filter} +<src/HAL/RP2040>
lib_deps         = ${common.lib_deps}
                   arduino-libraries/Servo
                   https://github.com/adafruit/Adafruit_ADS1X15
lib_ignore       = WiFi
board_build.variant = MARLIN_RP2040_PickSix
build_flags      = ${common.build_flags}
                   -IMarlin/src/HAL/RP2040/u8g
                   -D__PLAT_RP2040__
                   -DPLATFORM_M997_SUPPORT
                   -DNO_SD_HOST_DRIVE
                   -DNO_SOFTWARE_SERIAL
                   -Wno-expansion-to-defined
                   -Wno-vla
                   -Wno-ignored-qualifiers
                   -Wno-deprecated-declarations
                   -L${platformio.core_dir}/packages/framework-arduino-mbed/variants/RASPBERRY_PI_PICO/libs
upload_protocol  = jlink
debug_tool       = jlink
debug_server     = ${platformio.packages_dir}/tool-openocd-raspberrypi/bin/openocd
                   -f
                   ${PROJECT_DIR}/buildroot/share/PlatformIO/debugging/pico.ocd

[env:RP2040-alt]
extends          = env:RP2040
platform         = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.core = earlephilhower
debug_port = <your_jtag_interface>
#
# BigTreeTech SKR Pico 1.x
#
[env:SKR_Pico]
extends           = env:RP2040
lib_deps          = ${common.lib_deps}
                    arduino-libraries/Servo
